// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFjMeLBTrhDWB5Hv9pL5S15Z45uys1PoY',
    appId: '1:862137249582:web:ab9d203703b156901414bf',
    messagingSenderId: '862137249582',
    projectId: 'pitchme-a5578',
    authDomain: 'pitchme-a5578.firebaseapp.com',
    storageBucket: 'pitchme-a5578.appspot.com',
    measurementId: 'G-TCWWWP1SVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdrW70vdj-Xs8BIi4baEMELq0mLklmONU',
    appId: '1:862137249582:android:0e52be29fca416791414bf',
    messagingSenderId: '862137249582',
    projectId: 'pitchme-a5578',
    storageBucket: 'pitchme-a5578.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKeagUuxhg9F-UW66M_zmfjUm0fHujeX4',
    appId: '1:862137249582:ios:101aa3a4440121bc1414bf',
    messagingSenderId: '862137249582',
    projectId: 'pitchme-a5578',
    storageBucket: 'pitchme-a5578.appspot.com',
    iosBundleId: 'com.example.pitchme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKeagUuxhg9F-UW66M_zmfjUm0fHujeX4',
    appId: '1:862137249582:ios:101aa3a4440121bc1414bf',
    messagingSenderId: '862137249582',
    projectId: 'pitchme-a5578',
    storageBucket: 'pitchme-a5578.appspot.com',
    iosBundleId: 'com.example.pitchme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFjMeLBTrhDWB5Hv9pL5S15Z45uys1PoY',
    appId: '1:862137249582:web:551a157d22e861c31414bf',
    messagingSenderId: '862137249582',
    projectId: 'pitchme-a5578',
    authDomain: 'pitchme-a5578.firebaseapp.com',
    storageBucket: 'pitchme-a5578.appspot.com',
    measurementId: 'G-QESDM3YMHL',
  );
}
